"""empty message

Revision ID: 323197d36230
Revises: 5762ed9b0246
Create Date: 2020-12-23 15:46:06.814801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323197d36230'
down_revision = '5762ed9b0246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PublicAD_title_key', 'PublicAD', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('PublicAD_title_key', 'PublicAD', ['title'])
    # ### end Alembic commands ###
