"""empty message

Revision ID: 598fd65c13ca
Revises: b15ca3de666f
Create Date: 2020-12-26 01:22:42.030402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598fd65c13ca'
down_revision = 'b15ca3de666f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LocalAD', sa.Column('user_phone', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LocalAD', 'user_phone')
    # ### end Alembic commands ###
