"""empty message

Revision ID: a82d828a9a94
Revises: 41e4208b82be
Create Date: 2020-12-25 04:16:51.832043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82d828a9a94'
down_revision = '41e4208b82be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Cities', ['name'])
    op.add_column('Users', sa.Column('city_name', sa.String(), nullable=True))
    op.drop_constraint('Users_city_id_fkey', 'Users', type_='foreignkey')
    op.create_foreign_key(None, 'Users', 'Cities', ['city_name'], ['name'])
    op.drop_column('Users', 'city_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.create_foreign_key('Users_city_id_fkey', 'Users', 'Cities', ['city_id'], ['id'])
    op.drop_column('Users', 'city_name')
    op.drop_constraint(None, 'Cities', type_='unique')
    # ### end Alembic commands ###
