"""empty message

Revision ID: b15ca3de666f
Revises: a82d828a9a94
Create Date: 2020-12-25 15:39:17.414678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15ca3de666f'
down_revision = 'a82d828a9a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LocalAD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('author_fullname', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_fullname'], ['Users.fullname'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LocalAD')
    # ### end Alembic commands ###
